pipeline {
    agent any
    parameters {
        string(name: 'login', defaultValue: '', description: 'Username to login into the server')
        string(name: 'name', defaultValue: '', description: 'First Name and Last Name')
        choice(name: 'department', choices: ['accounting', 'finance', 'technology'], description: 'Choose department for the user')
    }
    stages {
        stage('Validation') {
            steps {
                script {
                    if (!params.login) {
                        error "Parameter 'login' is required."
                    }
                    if (!params.name) {
                        error "Parameter 'name' is required."
                    }
                    if (!params.department) {
                        error "Parameter 'department' is required."
                    }
                }
            }
        }
        stage('Create User') {
            steps {
                script {
                    def tempPassword = sh(script: "openssl rand -base64 10", , returnStdout: true).trim()
                    def encrPassword = sh(script: "openssl passwd -1 ${tempPassword}", returnStdout: true).trim()

                    sh '''
                        sudo useradd $LOGIN \
                            -m -s /bin/bash -d /home/$LOGIN \
                            -c "$NAME,$DEPARTMENT" \
                            -p "$ENC_PASSWORD"

                        sudo chage -d 0 ${params.login}
                    ''', env: [
                        "LOGIN=${params.login}",
                        "NAME=${params.name}",
                        "DEPARTMENT=${params.department}",
                        "ENC_PASSWORD=${encPassword}"
                    ]

                    echo "User ${params.login} created"
                    echo "Password: ${tempPassword}"
                }
            }
        }
    }
}
