def tempPassword() {
    def password = sh(script: "openssl rand -base64 10", returnStdout: true).trim()
    return password
}

pipeline {
    agent any
    parameters {
        string(name: 'login', defaultValue: '', description: 'Username to login into the server')
        string(name: 'name', defaultValue: '', description: 'First Name and Last Name')
        choice(name: 'department', choices: ['accounting', 'finance', 'technology'], description: 'Choose department for the user')
    }
    stages {
        stage('Validation') {
            steps {
                script {
                    if (!params.login) {
                        error "Parameter 'login' is required."
                    }
                    if (!params.name) {
                        error "Parameter 'name' is required."
                    }
                    if (!params.department) {
                        error "Parameter 'department' is required."
                    }
                }
            }
        }
        stage('Create temporal password') {
            steps {
                script {
                    env.PASSWORD = tempPassword()
                    echo "Temporal password created."
                }
            }
        }
        stage('Create User') {
            steps {
                script {

                    sh """
                        sudo useradd ${params.login} \
                            -m -s /bin/bash -d /home/${params.login} \
                            -c "${params.name},${params.department}" \
                            -p \$(echo "${env.PASSWORD}" | openssl passwd -1 -stdin)
                    """
                }
            }
        }
        stage('Assign user to group') {
            steps {
                script {
                    sh "sudo usermod -aG ${params.department} ${params.login}"
                }
            }
        }
        stage('Force password expiration') {
            steps {
                script {
                    sh "sudo passwd -e ${params.login}"
                }
            }
        }
    }
    post {
        success {
                echo "User ${params.login} created."
                echo "User ${params.login} assigned to group ${params.department}."
                echo "Password: ${env.PASSWORD}"
        }
        aborted {
            echo "Job cancelled."
            sh "sudo userdel -rf ${params.login}"
        }
        failure {
            echo "User could not be created."
            sh "sudo userdel -rf ${params.login}"
        }
    }
}
