jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"

jobs:
  - script: >
      folder('UserManagement')

  - script: >
      pipelineJob('UserManagement/UserCreation') {
        description('Job that creates user on Linux Server')
        parameters {
            stringParam('login', '', 'Username to login into the server')
            stringParam('name', '', 'First Name and Last Name')
            choiceParam('department', ['accounting', 'finance', 'technology'], 'Choose department for the user')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/nmema/jenkins-user-management.git')
                }
                branches('*/main')
              }
              scriptPath('user-creation/Jenkinsfile')
            }
          }
        }
      }

  - script: >
      pipelineJob('UserManagement/UserDeletion') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/nmema/jenkins-user-management.git')
                }
                branches('*/main')
              }
              scriptPath('user-deletion/Jenkinsfile')
            }
          }
        }
      }
