pipeline {
    agent any
    parameters {
        string(name: 'username', defaultValue: '', description: 'Username to delete from the server')
    }
    stages {
        stage('Validation') {
            steps {
                script {
                    if (!params.username) {
                        error "Parameter 'username' is required."
                    }
                
                    def username = params.username.trim()

                    def userExists = sh(
                        script: """
                            if id '${username}' >/dev/null 2>&1; then
                                echo 'true'
                            else
                                echo 'false'
                            fi
                        """,
                        returnStdout: true
                    ).trim()

                    if (userExists == 'false') {
                        error "User ${params.username} does not exist."
                    }

                }
            }
        }
        stage('Delete User') {
            steps {
                script {
                    sh "sudo userdel -rf ${params.username}"
                }
            }
        }
    }
    post {
        success {
            echo "User ${params.username} deleted"
        }
        aborted {
            echo "Job cancelled."
        }
        failure {
            echo "User could not be deleted."
        }
    }
}
